spring:
  application:
    name: Order-Service

  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?createDatabaseIfNotExist=true
    username: root
    password: "Prajwal@123"
    driver-class-name: com.mysql.cj.jdbc.Driver
